# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MyForm(object):
    def setupUi(self, MyForm):
        MyForm.setObjectName("MyForm")
        MyForm.resize(300, 200)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MyForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(MyForm)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btnOpen = QtWidgets.QPushButton(MyForm)
        self.btnOpen.setObjectName("btnOpen")
        self.verticalLayout.addWidget(self.btnOpen)
        self.btnQuit = QtWidgets.QPushButton(MyForm)
        self.btnQuit.setObjectName("btnQuit")
        self.verticalLayout.addWidget(self.btnQuit)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MyForm)
        QtCore.QMetaObject.connectSlotsByName(MyForm)

    def retranslateUi(self, MyForm):
        _translate = QtCore.QCoreApplication.translate
        MyForm.setWindowTitle(_translate("MyForm", "АЧХ сигнала"))
        self.label.setText(_translate("MyForm", "Данная утилита производит расчет амплитудно-частотной характеристики "
                                                "(АЧХ) исследуемого сигнала. Для определения АЧХ необходимо выбрать "
                                                "исследуемый сигнал."))
        self.btnOpen.setText(_translate("MyForm", "Выбрать и открыть файл"))
        self.btnQuit.setText(_translate("MyForm", "Отмена и Закрыть окно"))
